name: Deploy Nemo Stock to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 백엔드 .env 파일 생성
      - name: Create Backend .env
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > ./backend/.env

      # 프론트엔드 .env.production 파일 생성
      - name: Create Frontend .env
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > ./frontend/.env

      # Docker 컨테이너 빌드 및 재시작
      - name: Build and Restart Docker Containers
        run: |
          docker compose up -d --build

      # 미사용 이미지 정리
      - name: Cleanup unused Docker images
        run: |
          docker image prune -f
